### ISSUE TITLE
Static x86 control flow graph inserts bad instruction

### ISSUE THREAD

**Issue by HoLLy-HaCKeR** [Washi1337/Echo#38]
When using Echo to disassembly a certain certain function, some instructions seem to be incorrectly read (while they do work when using just Iced).

Project to reproduce: [EchoIssue.zip](https://github.com/Washi1337/Echo/files/4942886/EchoIssue.zip)
<details>
<summary>Iced vs Echo disassembly</summary>
<pre>
Iced:
0x0     89 E0:               mov eax,esp
0x2     90:                  nop
0x3     53:                  push ebx
0x4     57:                  push edi
0x5     56:                  push esi
0x6     29 E0:               sub eax,esp
0x8     83 F8 18:            cmp eax,18h
0xB     74 07:               je short 00000014h
0xD     8B 44 24 10:         mov eax,[esp+10h]
0x11    50:                  push eax
0x12    EB 01:               jmp short 00000015h
0x14    51:                  push ecx
0x15    58:                  pop eax
0x16    F7 D8:               neg eax
0x18    B9 59 42 9B 72:      mov ecx,729B4259h
0x1D    81 C1 43 47 D9 8E:   add ecx,8ED94743h
0x23    01 C8:               add eax,ecx
0x25    81 C0 72 5A E2 10:   add eax,10E25A72h
0x2B    5E:                  pop esi
0x2C    5F:                  pop edi
0x2D    5B:                  pop ebx
0x2E    C3:                  ret
</pre>
<pre>
Echo:
0x0     89 E0:               mov eax,esp
0x2     90:                  nop
0x3     53:                  push ebx
0x4     57:                  push edi
0x5     56:                  push esi
0x6     29 E0:               sub eax,esp
0x8     83 F8 18:            cmp eax,18h
0xB     74 07:               je short 00000014h
0xD     8B 44 24 10:         mov eax,[esp+10h]
0x11    50:                  push eax
0x12    EB 01:               jmp short 00000015h
0x14    :                    (bad)
0x15    58:                  push ecx
0x16    F7:                  pop eax
0x17    D8 B9:               neg eax
0x19    59 42 9B 72 81:      mov ecx,729B4259h
0x1E    C1 43 47 D9 8E 01:   add ecx,8ED94743h
0x24    C8 81:               add eax,ecx
0x26    C0 72 5A E2 10 5E:   add eax,10E25A72h
0x2C    5F:                  pop esi
0x2D    5B:                  pop edi
0x2E    C3:                  pop ebx
0x2F    :                    ret
</pre>
</details>

---

This function gave me a different error in a different environment. I'm not sure if this is useful, but I figured I'd add it anyway.
When using it in a dnSpy extension, reading from `StreamCodeReader`, the following exception occurs (I had to upgrade Iced to 1.8.0, shouldn't be related?):

```
System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Echo.ControlFlow.Collections.NodeCollection`1.get_Item(Int64 offset) in F:\Projects\DotNet\dnSpy.Extension.HoLLy\Echo\src\Core\Echo.ControlFlow\Collections\NodeCollection.cs:line 35
   at Echo.ControlFlow.ControlFlowGraph`1.GetNodeByOffset(Int64 offset) in F:\Projects\DotNet\dnSpy.Extension.HoLLy\Echo\src\Core\Echo.ControlFlow\ControlFlowGraph.cs:line 88
   at Echo.ControlFlow.Construction.FlowGraphBuilderBase`1.ConnectNodes(ControlFlowGraph`1 graph, IInstructionTraversalResult`1 traversalResult) in F:\Projects\DotNet\dnSpy.Extension.HoLLy\Echo\src\Core\Echo.ControlFlow\Construction\FlowGraphBuilderBase.cs:line 82
   at Echo.ControlFlow.Construction.FlowGraphBuilderBase`1.ConstructFlowGraph(Int64 entrypoint, IEnumerable`1 knownBlockHeaders) in F:\Projects\DotNet\dnSpy.Extension.HoLLy\Echo\src\Core\Echo.ControlFlow\Construction\FlowGraphBuilderBase.cs:line 28
   at Echo.ControlFlow.Construction.FlowGraphBuilderExtensions.ConstructFlowGraph[TInstruction](IFlowGraphBuilder`1 self, Int64 entrypoint) in F:\Projects\DotNet\dnSpy.Extension.HoLLy\Echo\src\Core\Echo.ControlFlow\Construction\IFlowGraphBuilder.cs:line 53
   at HoLLy.dnSpyExtension.NativeDisassembler.IcedHelpers.ReadNativeFunction(String loc, UInt32 fileOffset, Boolean is32Bit, UInt32 rva) in F:\Projects\DotNet\dnSpy.Extension.HoLLy\dnSpy.Extension.HoLLy\NativeDisassembler\IcedHelpers.cs:line 45
   at HoLLy.dnSpyExtension.NativeDisassembler.IcedHelpers.ReadNativeMethodBody(MethodDef method) in F:\Projects\DotNet\dnSpy.Extension.HoLLy\dnSpy.Extension.HoLLy\NativeDisassembler\IcedHelpers.cs:line 27
   at HoLLy.dnSpyExtension.NativeDisassembler.IcedHelpers.ReadNativeMethodBodyBytes(MethodDef method) in F:\Projects\DotNet\dnSpy.Extension.HoLLy\dnSpy.Extension.HoLLy\NativeDisassembler\IcedHelpers.cs:line 17
   at HoLLy.dnSpyExtension.NativeDisassembler.Commands.DisassembleNativeMethod.Execute(IMenuItemContext context) in F:\Projects\DotNet\dnSpy.Extension.HoLLy\dnSpy.Extension.HoLLy\NativeDisassembler\Commands\DisassembleNativeMethod.cs:line 28
   at dnSpy.Menus.MenuService.<>c__DisplayClass15_0.<Create>b__1(Object a) in F:\Projects\DotNet\dnSpy.Extension.HoLLy\dnSpy\dnSpy\dnSpy\Menus\MenuService.cs:line 345
   at dnSpy.Contracts.MVVM.RelayCommand.System.Windows.Input.ICommand.Execute(Object parameter) in F:\Projects\DotNet\dnSpy.Extension.HoLLy\dnSpy\dnSpy\dnSpy.Contracts.DnSpy\MVVM\RelayCommand.cs:line 49
   at MS.Internal.Commands.CommandHelpers.CriticalExecuteCommandSource(ICommandSource commandSource, Boolean userInitiated)
   at System.Windows.Controls.MenuItem.InvokeClickAfterRender(Object arg)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

I did a little bit of digging, and on the line `var successorNode = graph.GetNodeByOffset(successor.DestinationAddress);` in `ConnectNodes`, `successor.DestinationAddress` has value 0xAF39, where the entrypoint was 0xAF24 (same code as disassembly above). So, it tries to jump to the instruction at 0x15, which is right after the `(bad)` instruction, but the `(bad)` instruction is not part of the collected instructions.

**Comment by HoLLy-HaCKeR** [comment]
Looked into it closer. During `CollectInstructions`, for whatever reason `Instructions.GetInstructionAtOffset(long)` reads 1 byte past where it should. I looked at it for a while but I'm not smart enough to figure out why this happens. At this point I think it's just an Iced bug.

**Comment by Washi1337** [comment]
Seems to be a limitation of Iced (0xd4d/iced#110). We cannot easily update the current offset of a `CodeReader` object it seems. Therefore the recursive traversal disassembly fails.

There is a workaround that I have in mind but let's see first if there will be official support for setting the current offset.

**Comment by Washi1337** [comment]
Since `CodeReader` will not have any property or method to set the current offset, the `X86DecoderInstructionProvider` class was changed to accept a raw code stream instead of a `Decoder` object.
